#ifndef KDEVELOP_FULLVERSION_H
#define KDEVELOP_FULLVERSION_H

/* kdevelop-fullversion.h.  Generated by cmake from kdevelop-fullversion.h.cmake */

#define FULLVERSION "@KDevelop_FULL_VERSION@"

#endif //  KDEVELOP_FULLVERSION_H
